# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e19084024295bd1fa04662a711844a11972f1305409cbe378286d99c488def3e784180f1cb2fd40ca0ef8ecd99c60f15a9aa9862aa394b5be776337be189f3a

test:
  secret_key_base: 7a2d374798b3747b787f5400b6fd2f705c3cb68ae6f71d36d9676222af5f1aa0e7f1b736f22613c64f24c5e2f20cf4a3ddaac395d768597b26eb8aadb34dc567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
